russhousley/pyasn1-alt-modules

CHANGES.txt, pyasn1_alt_modules/rfc8894.py, tests/test_rfc8894.py
Add module and rest for RFC 8894.
=> Add RFC8894

CHANGES.txt, pyasn1_alt_modules/rfc9118.py, tests/__main__.py, tests/test_rfc9118.py
Add support for RFC 9118 and an associated test module
=> Add support for RFC 9118

CHANGES.txt, pyasn1_alt_modules/rfc2743.py, tests/__main__.py, tests/test_rfc2743.py
Add module and test for RFC 2743
=> Add support for RFC 2743

CHANGES.txt, pyasn1_alt_modules/rfc9174.py, tests/__main__.py, tests/test_rfc9174.py
Add module and test for RFC 9174.
=> Add RFC 9174

CHANGES.txt, tests/test_rfc9174.py
Improve the test for RFC9174 with a better certificate and opentypes checking.
=> Improve the test for RFC9174

CHANGES.txt, travis.yml
Add Python 3.9 and Python 3.10
=> Add Python 3.9 and Python 3.10

CHANGES.txt, pyasn1_alt_modules/rfc9215.py, tests/__main__.py, tests/test_rfc9215.py
Add module and tests for RFC 9215
=> Add support for RFC 9215

CHANGES.txt, pyasn1_alt_modules/rfc5698.py, tests/__main__.py, tests/test_rfc5698.py
Add module and test for RFC 5698
=> Add support for RFC 5698

CHANGES.txt, pyasn1_alt_modules/rfc9286.py, tests/__main__.py, tests/test_rfc9286.py
Add module and test for RFC 9286, which obsoletes RFC 6486.
=> Add support for RFC 9286

CHANGES.txt, tests/test_rfc2985.py, tests/test_rfc3370.py, tests/test_rfc3657.py, tests/test_rfc4010.py, tests/test_rfc4055.py, tests/test_rfc6494.py, tests/test_rfc7914.py, tests/test_rfc8692.py
Improve tests for RFC2985, RFC370, RFC3657, RFC4010, RFC4055, RFC6494, RFC7914, and RFC8692
=> Improve test routines

CHANGES.txt, pyasn1_alt_modules/rfc9289.py, tests/__main__.py, tests/test_rfc9289.py
Add module and test for RFC 9289
=> Add support for RFC 9289

CHANGES.txt, pyasn1_alt_modules/rfc9336.py, tests/__main__.py, tests/test_rfc9336.py
Add module and tests for RFC 9336
=> Add support for RFC 9336

pyasn1_alt_modules/rfc8708.py
Correct comment; it should reference pk_HSS_LMS_HashSig['subjectPublicKey'].
=> Fix typo in comment

CHANGES.txt, pyasn1_alt_modules/rfc9310.py, tests/__main__.py, tests/test_rfc9310.py
Add module and test for RFC 9310
=> Add support for RFC 9310

CHANGES.txt, pyasn1_alt_modules/rfc3546.py, tests/__main__.py, tests/test_rfc3546.py
Add module and test for RFC 3546.
=> Add support for RFC 3546

CHANGES.txt, pyasn1_alt_modules/rfc4366.py, tests/__main__.py, tests/test_rfc4366.py
Add module and test for RFC 4366
=> Add support for RFC 4366

CHANGES.txt, pyasn1_alt_modules/rfc9399.py, tests/__main__.py, tests/test_rfc9399.py
Add module and test for RFC 9399
=> Add support for RFC 9399

CHANGES.txt, pyasn1_alt_modules/addon.py
Fixed import-related bugs in addon.py for RelativeOID handling
=> Fix import-related bugs in addon.py

LICENSE.txt, README.md
Update copyright statements and fix a small typo.
=> Update LICENSE.txt and README.md

pyasn1_alt_modules/rfc9345.py, tests/test_rfc9345.py
=> Fix typo in OID name

CHANGES.txt, pyasn1_alt_modules/rfc9481.py, tests/__main__.py, tests/test_rfc9481.py
Add module and test for RFC 9481.
=> Add rfc9481

CHANGES.txt, pyasn1_alt_modules/rfc9509.py, tests/__main__.py, tests/test_rfc9509.py
Add module and test for RFC 9509.
=> Add support for RFC 9509

CHANGES.txt, pyasn1_alt_modules/rfc9548.py, tests/__main__.py, tests/test_rfc9548.py
Add module and test for RFC 9548
=> Add support for RFC 9548

CHANGES.txt, pyasn1_alt_modules/rfc9598.py, tests/__main__.py, tests/test_rfc9598.py
Add module and test for RFC 9598
=> Add support for RFC 9598

CHANGES.txt, pyasn1_alt_modules/rfc9582.py, tests/__main__.py, tests/test_rfc9582.py
Add module and test for RFC 9582
=> Add support for RFC 9582

CHANGES.txt, pyasn1_alt_modules/rfc9579.py, tests/__main__.py, tests/test_rfc9579.py
Add module and test for RFC 9579
=> Add support for RFC 9579

CHANGES.txt, pyasn1_alt_modules/rfc9480.py
Add updates to the algorithm identifier map to RFC 9480
=> Add algorithm identifier map to RFC 9480

CHANGES.txt, pyasn1_alt_modules/rfc9480.py
Correct typo in SignKeyPairTypesValue.
=> Fix typo in RFC 9480

tests/test_rfc8708.py
Update the RFC 8707 tests for errata eid7963.
=> Update the tests for RFC 8708

CHANGES.txt, pyasn1_alt_modules/rfc9608.py, tests/__main__.py, tests/test_rfc9608.py
Add module and test for RFC 9608
=> Add support for RFC 9608

CHANGES.txt, pyasn1_alt_modules/rfc6402.py
Modified for errata 3943, 5931, and 6571.
=> Fix errata for RFC 6402

CHANGES.txt, pyasn1_alt_modules/rfc9629.py, tests/__main__.py, tests/test_rfc9629.py
Add module and test for RFC 9629.
=> Add support for RFC 9629

CHANGES.txt, pyasn1_alt_modules/rfc9654.py, tests/__main__.py, tests/test_rfc9654.py
=> Add support for RFC 9654

CHANGES.txt, pyasn1_alt_modules/rfc9688.py, tests/__main__.py, tests/test_rfc9688.py
Add module and test for RFC 9688.
=> Add support for RFC 9688

CHANGES.txt, pyasn1_alt_modules/rfc9688.py, pyasn1_alt_modules/rfc9691.py, tests/__main__.py, tests/test_rfc9691.py
Add module and test for RFC 9691.  Also, improve RFC 9688 handling of KDF2 and KDF3 entries in algorithm identifier map.
=> Add support for RFC 9691

CHANGES.txt, pyasn1_alt_modules/rfc9708.py, tests/__main__.py, tests/test_rfc9708.py
Add module and test for RFC 9708
=> Add support for RFC 9708

CHANGES.txt, pyasn1_alt_modules/rfc9690.py, tests/__main__.py, tests/test_rfc9690.py
Module and tests for RFC 9690.
=> Add support for RFC 9690

CHANGES.txt, pyasn1_alt_modules/rfc9734.py, tests/__main__.py, tests/test_rfc9734.py
Add module and test for RFC 9734
=> Add support for RFC 9734

CHANGES.txt, pyasn1_alt_modules/rfc9763.py, tests/__main__.py, tests/test_rfc9763.py
Add module and test for RFC 9763
=> Add support for RFC 9763

CHANGES.txt, pyasn1_alt_modules/rfc8295.py, tests/__main__.py, tests/test_rfc8295.py
Add module and test for RFC 8295
=> Add support for RFC 8295

CHANGES.txt, pyasn1_alt_modules/rfc9802.py, tests/__main__.py, tests/test_rfc9802.py
Add module and test for RFC 9802
=> Add support for RFC 9802

CHANGES.txt, pyasn1_alt_modules/rfc9810.py, tests/__main__.py, tests/test_rfc9810.py
Add module and test for RFC 9810.
=> Add support for RFC 9810

CHANGES.txt, pyasn1_alt_modules/rfc9809.py, tests/__main__.py, tests/test_rfc9809.py
Add module and test for RFC 9809
=> Add support for RFC 9809
